// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otmcnzsmzeixpttwslgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90bWNuenNtemVpeHB0dHdzbGdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNjA1ODEsImV4cCI6MjA2ODczNjU4MX0.2uUHUqXh9CiViYOLdLsPQ_66tPMnIsWsCs71Sxo-mjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});